[package]
name = "sqlx-crud-macros"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/treydempsey/sqlx-crud"
documentation = "https://docs.rs/sqlx-crud"
description = "Proc macro implemtation for sqlx-crud to implement Create, Read, Update, and Delete (CRUD) methods on SQLx for you ğŸª„ ğŸ“– ğŸ“ âŒ"
license = "MIT"
keywords = ["sqlx", "orm", "crud", "database"]
categories = ["database", "asynchronous", "web-programming"]
authors = ["Trey Dempsey <trey.dempsey@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
Inflector = "0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
