[workspace]
members = [
  ".",
  "sqlx-crud-macros",
]

[package]
name = "sqlx-crud"
version = "0.3.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/treydempsey/sqlx-crud"
documentation = "https://docs.rs/sqlx-crud"
description = "Derive macro for SQLx to implement Create, Read, Update, and Delete (CRUD) methods for you ğŸª„ ğŸ“– ğŸ“ âŒ"
license = "MIT"
keywords = ["sqlx", "orm", "crud", "database"]
categories = ["database", "asynchronous", "web-programming"]
authors = ["Trey Dempsey <trey.dempsey@gmail.com>"]

[features]
default = ["runtime-tokio-rustls"]
runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

[dependencies]
futures = "0"
sqlx = { version = "0" }
sqlx-crud-macros = { version = "0.3", path = "sqlx-crud-macros" }
thiserror = "1"

[dev-dependencies]
sqlx = { version = "0", features = ["runtime-tokio-rustls", "sqlite"] }
tokio-test = "0"
